baseURL = "https://example.com"
title = "Wood Programming Language"
languageCode = "en-us"

contentDir = "hugo-content"       # Default was "content"
layoutDir = "hugo-layouts"        # Default was "layouts"
staticDir = "hugo-static"         # Default was "static"

[params]
snippetsDir = "hugo-static/snippets"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2